@echo off
echo Starting Frontend on port 3000...
cd /d "e:\UMT\FYP\Ultimate final version for FYP-1\khizer fyp\khizer fyp\serenemind\frontend"
echo Installing dependencies...
call npm install
echo Starting Next.js dev server...
set NEXT_PUBLIC_API_URL=http://localhost:3000/api
call npm run dev
